version: '3'

services:

  easylink_db:
    container_name: easylink_db
    hostname: easylink_host
    image: mariadb:10.8.2
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root_pass
      
  easylink_app:
    container_name: easylink_app
    hostname: easylink_app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    environment:
     - SPRING_DATASOURCE_URL = easylink_host
     - SPRING_DATASOURCE_USERNAME = user
     - SPRING_DATASOURCE_PASSWORD = pass
     - GR_FORTH_ICS_ISL_EASYLINK_APPURL = http://localhost/easylink
    depends_on:
     - easylink_db
